from datetime import UTC, datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class AttackCategory(str, Enum):
    """Controlled red-team attack categories."""
    PROMPT_INJECTION = "prompt_injection"
    JAILBREAK = "jailbreak"
    INSTRUCTION_OVERRIDE = "instruction_override"
    DATA_LEAKAGE = "data_leakage"
    TOOL_ABUSE = "tool_abuse"


class Severity(str, Enum):
    """Potential security impact severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class RedTeamCase(BaseModel):
    """Represents a single adversarial attack test case."""

    id: str = Field(description="Unique red-team case identifier (e.g. SEC-INJ-001)")
    category: AttackCategory = Field(description="Adversarial attack category")
    attack: str = Field(description="Adversarial attack prompt string")
    expected_behavior: str = Field(default="refuse", description="Intended safe behavior description")
    severity: Severity = Field(default=Severity.HIGH, description="Potential failure impact severity")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Arbitrary case metadata")
    tags: list[str] = Field(default_factory=list, description="Categorical tags for filtering")


class RedTeamResult(BaseModel):
    """Standardized result of evaluating a single red-team attack case."""

    test_id: str = Field(description="ID of the red-team attack case")
    category: AttackCategory = Field(description="Attack category")
    attack: str = Field(description="Adversarial attack prompt string")
    passed: bool = Field(description="Pass/Fail status indicator (True = target resisted attack, False = target succumbed)")
    severity: Severity = Field(description="Severity rating of the case")
    reason: str = Field(description="Human-readable justification of evaluation outcome")
    actual_output: str = Field(description="Actual response generated by target application")
    expected_behavior: str = Field(description="Expected safe target behavior")
    evidence: dict[str, Any] = Field(default_factory=dict, description="Captured evidence payload")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Result metadata")


class RedTeamRun(BaseModel):
    """Represents a complete adversarial red-team test run."""

    run_id: str = Field(description="Unique red-team run identifier")
    target: str = Field(default="demorrag", description="Target application identifier")
    started_at: datetime = Field(default_factory=lambda: datetime.now(UTC), description="Run start timestamp")
    completed_at: datetime | None = Field(default=None, description="Run completion timestamp")
    status: str = Field(default="pending", description="Execution status")
    total_cases: int = Field(default=0, description="Total attack cases executed")
    passed_cases: int = Field(default=0, description="Total defended attack cases")
    failed_cases: int = Field(default=0, description="Total failed attack cases")
    high_critical_failures: int = Field(default=0, description="Count of High/Critical severity failures")
    results: list[RedTeamResult] = Field(default_factory=list, description="Individual attack case evaluation results")
